In [65]:
import pandas as pd

# CSV 파일 불러오기
csv_filename = "./review_by_gpt.csv"
df = pd.read_csv(csv_filename, encoding="utf-8-sig")

# 데이터 확인
print(df.head())

                                    리뷰  속성  감성
0  패키지가 귀엽고 개별 포장이라서 가방에 쏙 넣고 다니기 좋아요.  포장  긍정
1       전자레인지 조리 가능하지만, 조리 시간이 너무 길어요.  포장  중립
2         비슷한 제품 대비 너무 비쌉니다. 가성비 별로예요.  가격  부정
3          과자가 바삭하고 달콤해서 커피랑 먹기 딱 좋아요!   맛  긍정
4     예전 비슷한 제품이랑 비교하면 맛이 조금 더 연해진 느낌?   맛  중립

In [87]:
df

,리뷰,속성,감성,토큰화된 리뷰,속성_인코딩,감성_인코딩,input_ids,attention_mask
0,패키지가 귀엽고 개별 포장이라서 가방에 쏙 넣고 다니기 좋아요,포장,긍정,"[패키지가, 귀엽고, 개별, 포장이라서, 가방에, 쏙, 넣고, 다니기, 좋아요]",2,0,"[2, 3247, 4379, 8440, 25136, 4034, 27965, 1192...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,전자레인지 조리 가능하지만 조리 시간이 너무 길어요,포장,중립,"[전자레인지, 조리, 가능하지만, 조리, 시간이, 너무, 길어요]",2,2,"[2, 12116, 4306, 8148, 23537, 8545, 9082, 2353...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ..."
2,비슷한 제품 대비 너무 비쌉니다 가성비 별로예요,가격,부정,"[비슷한, 제품, 대비, 너무, 비쌉니다, 가성비, 별로예요]",0,1,"[2, 12649, 10868, 12279, 8069, 1664, 5857, 796...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, ..."
3,과자가 바삭하고 달콤해서 커피랑 먹기 딱 좋아요,맛,긍정,"[과자가, 바삭하고, 달콤해서, 커피랑, 먹기, 딱, 좋아요]",1,0,"[2, 321, 8102, 1480, 4914, 7968, 29286, 7987, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ..."
4,예전 비슷한 제품이랑 비교하면 맛이 조금 더 연해진 느낌,맛,중립,"[예전, 비슷한, 제품이랑, 비교하면, 맛이, 조금, 더, 연해진, 느낌]",1,2,"[2, 9979, 12649, 10868, 8277, 24373, 16235, 88...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ..."
...,...,...,...,...,...,...,...,...
95,뚜껑이 튼튼해서 가방에 넣고 다녀도 샐 걱정이 없어요,포장,긍정,"[뚜껑이, 튼튼해서, 가방에, 넣고, 다녀도, 샐, 걱정이, 없어요]",2,0,"[2, 1072, 4916, 4017, 20489, 7987, 20264, 4113...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
96,요즘 물가 생각하면 이 정도 가격에 이런 퀄리티라니 가성비 최고,가격,긍정,"[요즘, 물가, 생각하면, 이, 정도, 가격에, 이런, 퀄리티라니, 가성비, 최고]",0,0,"[2, 8380, 12551, 10906, 2451, 8384, 28919, 798...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ..."
97,전자레인지 조리 가능하다는데 포장이 터져서 난리났음,포장,부정,"[전자레인지, 조리, 가능하다는데, 포장이, 터져서, 난리났음]",2,1,"[2, 12116, 4306, 8148, 23537, 19300, 7972, 119...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
98,빵이 퍽퍽하고 속 내용물이 별로네요,맛,부정,"[빵이, 퍽퍽하고, 속, 내용물이, 별로네요]",1,1,"[2, 1692, 4017, 3264, 5424, 7968, 1896, 9132, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, ..."
99,신제품 라면 국물이 얼큰하고 깊은 맛이 나요 완전 취향 저격,맛,긍정,"[신제품, 라면, 국물이, 얼큰하고, 깊은, 맛이, 나요, 완전, 취향, 저격]",1,0,"[2, 2005, 10519, 13958, 348, 9463, 2240, 5277,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [66]:
import re

def clean_text(text):
    text = text.lower()  # 소문자 변환
    text = re.sub(r"[^가-힣a-zA-Z0-9\s]", "", text)  # 한글, 영어, 숫자만 남기기
    text = re.sub(r"\s+", " ", text).strip()  # 연속된 공백 제거
    return text

df["리뷰"] = df["리뷰"].apply(clean_text)

In [67]:
# 데이터 확인
print(df.head())

                                   리뷰  속성  감성
0  패키지가 귀엽고 개별 포장이라서 가방에 쏙 넣고 다니기 좋아요  포장  긍정
1        전자레인지 조리 가능하지만 조리 시간이 너무 길어요  포장  중립
2          비슷한 제품 대비 너무 비쌉니다 가성비 별로예요  가격  부정
3          과자가 바삭하고 달콤해서 커피랑 먹기 딱 좋아요   맛  긍정
4     예전 비슷한 제품이랑 비교하면 맛이 조금 더 연해진 느낌   맛  중립

# 데이터 전처리, 토큰화

In [68]:
from soynlp.tokenizer import RegexTokenizer

tokenizer = RegexTokenizer()
tokens = tokenizer.tokenize("이 편의점 신상품 너무 맛있어요!")
print(tokens)

['이', '편의점', '신상품', '너무', '맛있어요', '!']

C:\Users\playdata2\anaconda3\envs\nlp_env\lib\site-packages\soynlp\tokenizer\_tokenizer.py:19: FutureWarning: Possible nested set at position 13
  ('english & latin', re.compile(u"[a-zA-ZÀ-ÿ]+[[`']?s]*|[a-zA-ZÀ-ÿ]+", re.UNICODE))

In [69]:
from soynlp.tokenizer import RegexTokenizer

# ✅ soynlp 토큰화 수행
tokenizer = RegexTokenizer()
df["토큰화된 리뷰"] = df["리뷰"].apply(tokenizer.tokenize)

# ✅ 토큰화된 데이터 확인
print(df[["리뷰", "토큰화된 리뷰"]].head())

                                   리뷰  \
0  패키지가 귀엽고 개별 포장이라서 가방에 쏙 넣고 다니기 좋아요
1        전자레인지 조리 가능하지만 조리 시간이 너무 길어요
2          비슷한 제품 대비 너무 비쌉니다 가성비 별로예요
3          과자가 바삭하고 달콤해서 커피랑 먹기 딱 좋아요
4     예전 비슷한 제품이랑 비교하면 맛이 조금 더 연해진 느낌

                                        토큰화된 리뷰
0  [패키지가, 귀엽고, 개별, 포장이라서, 가방에, 쏙, 넣고, 다니기, 좋아요]
1          [전자레인지, 조리, 가능하지만, 조리, 시간이, 너무, 길어요]
2            [비슷한, 제품, 대비, 너무, 비쌉니다, 가성비, 별로예요]
3            [과자가, 바삭하고, 달콤해서, 커피랑, 먹기, 딱, 좋아요]
4     [예전, 비슷한, 제품이랑, 비교하면, 맛이, 조금, 더, 연해진, 느낌]

In [70]:
from sklearn.preprocessing import LabelEncoder

# ✅ 속성과 감성을 숫자로 변환
aspect_encoder = LabelEncoder()
sentiment_encoder = LabelEncoder()

df["속성_인코딩"] = aspect_encoder.fit_transform(df["속성"])
df["감성_인코딩"] = sentiment_encoder.fit_transform(df["감성"])

# ✅ 변환된 데이터 확인
print(df[["속성", "속성_인코딩", "감성", "감성_인코딩"]].head())

   속성  속성_인코딩  감성  감성_인코딩
0  포장       2  긍정       0
1  포장       2  중립       2
2  가격       0  부정       1
3   맛       1  긍정       0
4   맛       1  중립       2

In [71]:
from transformers import BertTokenizer

# ✅ BERT 토크나이저 로드
tokenizer = BertTokenizer.from_pretrained("beomi/kcbert-base")

# 최대 토큰 길이 설정
MAX_LEN = 64

def bert_tokenize(text):
    encoding = tokenizer(
        text,
        max_length=MAX_LEN,
        padding="max_length",
        truncation=True,
        return_tensors="pt"
    )
    return encoding["input_ids"][0].tolist(), encoding["attention_mask"][0].tolist()

df["input_ids"], df["attention_mask"] = zip(*df["리뷰"].apply(bert_tokenize))

# 모델 학습 및 평가

In [8]:
df.head()

,리뷰,속성,감성,토큰화된 리뷰,속성_인코딩,감성_인코딩,input_ids,attention_mask
0,패키지가 귀엽고 개별 포장이라서 가방에 쏙 넣고 다니기 좋아요,포장,긍정,"[패키지가, 귀엽고, 개별, 포장이라서, 가방에, 쏙, 넣고, 다니기, 좋아요]",2,0,"[2, 3247, 4379, 8440, 25136, 4034, 27965, 1192...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,전자레인지 조리 가능하지만 조리 시간이 너무 길어요,포장,중립,"[전자레인지, 조리, 가능하지만, 조리, 시간이, 너무, 길어요]",2,2,"[2, 12116, 4306, 8148, 23537, 8545, 9082, 2353...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ..."
2,비슷한 제품 대비 너무 비쌉니다 가성비 별로예요,가격,부정,"[비슷한, 제품, 대비, 너무, 비쌉니다, 가성비, 별로예요]",0,1,"[2, 12649, 10868, 12279, 8069, 1664, 5857, 796...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, ..."
3,과자가 바삭하고 달콤해서 커피랑 먹기 딱 좋아요,맛,긍정,"[과자가, 바삭하고, 달콤해서, 커피랑, 먹기, 딱, 좋아요]",1,0,"[2, 321, 8102, 1480, 4914, 7968, 29286, 7987, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ..."
4,예전 비슷한 제품이랑 비교하면 맛이 조금 더 연해진 느낌,맛,중립,"[예전, 비슷한, 제품이랑, 비교하면, 맛이, 조금, 더, 연해진, 느낌]",1,2,"[2, 9979, 12649, 10868, 8277, 24373, 16235, 88...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ..."

In [72]:
from sklearn.model_selection import train_test_split

# 입력 및 레이블 데이터
X = list(zip(df["input_ids"], df["attention_mask"]))
y_aspect = df["속성_인코딩"].values
y_sentiment = df["감성_인코딩"].values

# 데이터 분할
X_train, X_test, y_train_aspect, y_test_aspect, y_train_sentiment, y_test_sentiment = train_test_split(
    X, y_aspect, y_sentiment, test_size=0.2, random_state=42, stratify=y_sentiment
)

print(f"학습 데이터 개수: {len(X_train)}, 테스트 데이터 개수: {len(X_test)}")

학습 데이터 개수: 80, 테스트 데이터 개수: 20

In [73]:
import torch
from torch.utils.data import DataLoader, TensorDataset

# ✅ PyTorch Tensor 변환 (훈련 데이터)
train_inputs = torch.tensor([x[0] for x in X_train])
train_masks = torch.tensor([x[1] for x in X_train])
train_labels_aspect = torch.tensor(y_train_aspect)
train_labels_sentiment = torch.tensor(y_train_sentiment)

# ✅ PyTorch Tensor 변환 (테스트 데이터)
test_inputs = torch.tensor([x[0] for x in X_test])
test_masks = torch.tensor([x[1] for x in X_test])
test_labels_aspect = torch.tensor(y_test_aspect)
test_labels_sentiment = torch.tensor(y_test_sentiment)

# ✅ DataLoader 생성 (Batch Size = 8)
train_dataset = TensorDataset(train_inputs, train_masks, train_labels_aspect, train_labels_sentiment)
train_dataloader = DataLoader(train_dataset, batch_size=8, shuffle=True)

test_dataset = TensorDataset(test_inputs, test_masks, test_labels_aspect, test_labels_sentiment)
test_dataloader = DataLoader(test_dataset, batch_size=8, shuffle=False)

# ✅ 데이터 크기 확인
train_size = len(train_dataset)
test_size = len(test_dataset)
print(f"훈련 데이터 개수: {train_size}, 테스트 데이터 개수: {test_size}")

훈련 데이터 개수: 80, 테스트 데이터 개수: 20

In [74]:
from transformers import BertForSequenceClassification, AdamW

# ✅ GPU 사용 여부 확인
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ✅ BERT 모델 로드 (출력 레이블 3개: 속성 + 감성)
model = BertForSequenceClassification.from_pretrained("beomi/kcbert-base", num_labels=len(aspect_encoder.classes_) + len(sentiment_encoder.classes_))
model.to(device)

# ✅ 옵티마이저 및 손실 함수 설정
optimizer = AdamW(model.parameters(), lr=2e-5)
loss_fn = torch.nn.CrossEntropyLoss()

# ✅ 학습 실행
EPOCHS = 3

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0

    for batch in train_dataloader:
        batch = tuple(t.to(device) for t in batch)
        inputs, masks, labels_aspect, labels_sentiment = batch

        optimizer.zero_grad()
        outputs = model(inputs, attention_mask=masks)
        loss_aspect = loss_fn(outputs.logits[:, :len(aspect_encoder.classes_)], labels_aspect)
        loss_sentiment = loss_fn(outputs.logits[:, len(aspect_encoder.classes_):], labels_sentiment)

        loss = loss_aspect + loss_sentiment
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
    
    print(f"Epoch {epoch+1}/{EPOCHS}, Loss: {total_loss/len(train_dataloader):.4f}")

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at beomi/kcbert-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\playdata2\anaconda3\envs\nlp_env\lib\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

Epoch 1/3, Loss: 1.9483
Epoch 2/3, Loss: 1.2274
Epoch 3/3, Loss: 0.7329

In [12]:
# ✅ 학습 설정
EPOCHS = 3  # 학습 반복 횟수

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0

    for batch in train_dataloader:
        batch = tuple(t.to(device) for t in batch)  # GPU/CPU 이동
        inputs, masks, labels_aspect, labels_sentiment = batch

        optimizer.zero_grad()
        outputs = model(inputs, attention_mask=masks, labels=labels_sentiment)
        loss = outputs.loss
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
    
    print(f"Epoch {epoch+1}/{EPOCHS}, Loss: {total_loss/len(train_dataloader):.4f}")

Epoch 1/3, Loss: 0.9702
Epoch 2/3, Loss: 0.6972
Epoch 3/3, Loss: 0.3338

## 모델 평가- gpt 리뷰 일부

In [76]:
import numpy as np
from sklearn.metrics import accuracy_score
# ✅ 모델 저장
torch.save(model.state_dict(), "./absa_model.pth")

# ✅ 모델 로드 (테스트 실행)
model.load_state_dict(torch.load("./absa_model.pth"))
model.to(device)
model.eval()

# ✅ 모델 평가
import numpy as np
from sklearn.metrics import accuracy_score

predictions_aspect, predictions_sentiment, true_labels_aspect, true_labels_sentiment = [], [], [], []

with torch.no_grad():
    for batch in test_dataloader:
        batch = tuple(t.to(device) for t in batch)
        inputs, masks, labels_aspect, labels_sentiment = batch

        outputs = model(inputs, attention_mask=masks)
        logits = outputs.logits

        predictions_aspect.extend(torch.argmax(logits[:, :len(aspect_encoder.classes_)], dim=1).cpu().numpy())
        predictions_sentiment.extend(torch.argmax(logits[:, len(aspect_encoder.classes_):], dim=1).cpu().numpy())

        true_labels_aspect.extend(labels_aspect.cpu().numpy())
        true_labels_sentiment.extend(labels_sentiment.cpu().numpy())

# ✅ 정확도 출력
aspect_acc = accuracy_score(true_labels_aspect, predictions_aspect)
sentiment_acc = accuracy_score(true_labels_sentiment, predictions_sentiment)
print(f"속성 예측 정확도: {aspect_acc:.2f}, 감성 예측 정확도: {sentiment_acc:.2f}")

속성 예측 정확도: 1.00, 감성 예측 정확도: 0.90

In [21]:
import random
import numpy as np

# ✅ 테스트 데이터에서 랜덤으로 한 개 샘플 선택
sample_index = random.randint(0, len(X_test) - 1)
sample_input_ids = test_inputs[sample_index].unsqueeze(0).to(device)  # 배치 차원 추가
sample_attention_mask = test_masks[sample_index].unsqueeze(0).to(device)

# ✅ 해당 샘플의 원래 문장 가져오기
tokens = tokenizer.convert_ids_to_tokens(sample_input_ids.squeeze().tolist())
original_text = tokenizer.convert_tokens_to_string(tokens)

print(f"✅ 분석할 샘플 문장: {original_text}")

✅ 분석할 샘플 문장: [CLS] 전자레인지 조리 가능하다는데 포장이 터져서 난리났음 [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]

In [92]:
# ✅ 모델 평가 모드 설정
model.eval()

# ✅ 모델 예측 수행
with torch.no_grad():
    outputs = model(sample_input_ids, attention_mask=sample_attention_mask)
    logits = outputs.logits
    predicted_label = torch.argmax(logits, dim=1).cpu().item()

# ✅ 예측된 감성 레이블 변환
predicted_aspect = aspect_encoder.inverse_transform([predicted_label])[0]

print(f"✅ 예측된 속성: {predicted_aspect}")

✅ 예측된 속성: 포장

In [99]:
import torch
from captum.attr import IntegratedGradients

sentence = original_text

# Integrated Gradients 객체 생성
ig = IntegratedGradients(model)

# 올바른 input_ids 가져오기
sample_input_ids = sample_input_ids.to(device)

# 중요도 분석 실행 (차원 문제 해결)
aspect_target = 2
attributions = ig.attribute(sample_input_ids, target=aspect_target)

# 중요도가 높은 단어 찾기
tokens = tokenizer.convert_ids_to_tokens(sample_input_ids.squeeze().tolist())  # 토큰화
importance = attributions.squeeze().tolist()  # 중요도 변환

# 중요도가 높은 순서대로 정렬
important_words = sorted(zip(tokens, importance), key=lambda x: abs(x[1]), reverse=True)
print("속성 분류에 영향을 준 키워드:", important_words[:5])

RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

In [94]:
model.eval()

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30000, 768, padding_idx=0)
      (position_embeddings): Embedding(300, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=6, bias=True)
)

In [30]:
print("✅ 원본 문장 토큰:", tokens)

✅ 원본 문장 토큰: ['[CLS]', '전자', '##레', '##인지', '조리', '가능하다', '##는데', '포장', '##이', '터져', '##서', '난리', '##났', '##음', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']

In [37]:
from captum.attr import IntegratedGradients

# ✅ Integrated Gradients 해석기 로드
ig = IntegratedGradients(model)

# ✅ 모델 예측에 영향을 미친 단어의 기여도 계산 (Batch 차원 추가 + Tuple로 전달)
attributions = ig.attribute(
    inputs=(sample_input_ids.unsqueeze(0), sample_attention_mask.unsqueeze(0)),  # ✅ 올바른 입력값 전달
    target=predicted_label,  # ✅ 예측된 감성 레이블
)

print(f"attributions shape: {attributions.shape}")  # ✅ 예상: torch.Size([1, 문장 길이])


# ✅ 결과 출력
for token, score in zip(tokens, attributions[0].squeeze().tolist()):
    print(f"단어: {token}, 기여도: {score:.4f}")


# # ✅ 결과 출력
# for token, score in zip(tokens, attributions[0].squeeze().tolist()):  # ✅ 첫 번째 입력(`input_ids`)의 기여도만 출력
#     print(f"단어: {token}, 기여도: {score:.4f}")

ValueError: too many values to unpack (expected 2)

In [40]:
from captum.attr import IntegratedGradients

# ✅ Integrated Gradients 해석기 로드
ig = IntegratedGradients(model)
print(ig)

# ✅ 모델 예측에 영향을 미친 단어의 기여도 계산 (attention_mask는 additional_forward_args로 전달)
attributions = ig.attribute(
    inputs=sample_input_ids.unsqueeze(0),  # ✅ input_ids만 입력
    target=predicted_label,  # ✅ 예측된 감성 레이블
    additional_forward_args=(sample_attention_mask.unsqueeze(0),)  # ✅ attention_mask는 별도 전달
)

# ✅ 결과 출력
for token, score in zip(tokens, attributions.squeeze().tolist()):
    print(f"단어: {token}, 기여도: {score:.4f}")

<captum.attr._core.integrated_gradients.IntegratedGradients object at 0x00000257A6C370A0>

ValueError: too many values to unpack (expected 2)

## 모델 평가 - 인스타그램 크롤링

In [77]:
import pandas as pd
import torch
from transformers import BertTokenizer

# ✅ 새로운 리뷰 데이터 업로드
csv_filename = "./instagram_review.csv"  # 업로드한 파일 이름을 여기에 입력
df_new = pd.read_csv(csv_filename, encoding="utf-8-sig")

# ✅ 리뷰 데이터 확인
print(df_new.head())

         userid                                            content  \
0  gung_di_food  #광고#디저트39저당디저트★판매처:#편의점 (세븐일레븐 단독)#디저트39 와 콜라보...
1  gung_di_food  #티라미수젤라또★구매처:#이마트★가격:5,980원오랜만에 이마트 갔다가 아이스크림 ...
2  gung_di_food  #잘익은쑥이야기★구매처:#편의점#세븐일레븐#GS25#CU★가격:2,000원편의점 빵...
3  gung_di_food  #비타민나무카라멜★구매처:#쿠팡#쿠팡로켓배송★가격: 3봉지 세트로 8,520원티벳에...
4  gung_di_food  #아이스홍시★구입처:#편의점#세븐일레븐★가격: 1,800원(할인행사가격)갑자기 아이...

         data                                               tags
0  2025-01-21  ['#광고', '#디저트39저당디저트★판매처:', '#편의점', '#디저트39', ...
1  2025-01-19  ['#티라미수젤라또★구매처:', '#이마트★가격:5', '#이마트추천', '#이마트...
2  2025-01-17  ['#잘익은쑥이야기★구매처:', '#편의점', '#세븐일레븐', '#GS25', '...
3  2025-01-16  ['#비타민나무카라멜★구매처:', '#쿠팡', '#쿠팡로켓배송★가격:', '#비타민...
4  2025-01-15  ['#아이스홍시★구입처:', '#편의점', '#세븐일레븐★가격:', '#편의점신상'...

In [78]:
df_new

,userid,content,data,tags
0,gung_di_food,#광고#디저트39저당디저트★판매처:#편의점 (세븐일레븐 단독)#디저트39 와 콜라보...,2025-01-21,"['#광고', '#디저트39저당디저트★판매처:', '#편의점', '#디저트39', ..."
1,gung_di_food,"#티라미수젤라또★구매처:#이마트★가격:5,980원오랜만에 이마트 갔다가 아이스크림 ...",2025-01-19,"['#티라미수젤라또★구매처:', '#이마트★가격:5', '#이마트추천', '#이마트..."
2,gung_di_food,"#잘익은쑥이야기★구매처:#편의점#세븐일레븐#GS25#CU★가격:2,000원편의점 빵...",2025-01-17,"['#잘익은쑥이야기★구매처:', '#편의점', '#세븐일레븐', '#GS25', '..."
3,gung_di_food,"#비타민나무카라멜★구매처:#쿠팡#쿠팡로켓배송★가격: 3봉지 세트로 8,520원티벳에...",2025-01-16,"['#비타민나무카라멜★구매처:', '#쿠팡', '#쿠팡로켓배송★가격:', '#비타민..."
4,gung_di_food,"#아이스홍시★구입처:#편의점#세븐일레븐★가격: 1,800원(할인행사가격)갑자기 아이...",2025-01-15,"['#아이스홍시★구입처:', '#편의점', '#세븐일레븐★가격:', '#편의점신상'..."
...,...,...,...,...
295,cho__food,스타벅스 신상으로 나온#메리베리베이글샌드⠀ 블루베리 베이글 + 베리맛 크림치즈+ 라...,2024-12-02,"['#메리베리베이글샌드⠀', '#스벅신메뉴', '#스벅신상', '#스타벅스베이글',..."
296,cho__food,#협찬 애슐리 퀸즈에서 11월 28일에 시즌한정으로스테이크&와인페어링이 출시되서 연...,2024-12-02,"['#협찬', '#애슐리퀸즈', '#애슐리퀸즈스테이크앤와인페어링', '#연말모임장소..."
297,cho__food,GS25편의점 신상으로 나온#누룽지우리쌀파운드⠀ 생각보다 부드럽고 촉촉한편이었고파운...,2024-12-01,"['#누룽지우리쌀파운드⠀', '#누룽지우리쌀파운드', '#누룽지', '#파운드', ..."
298,cho__food,신상과자로 나온 오리온#꼬래밥콘스프맛⠀ 기존 고래밥과 달리 거북이🐢모양으로되어 있고...,2024-11-28,"['#꼬래밥콘스프맛⠀', '#꼬래밥', '#신상과자', '#신상과자리뷰', '#오리..."
299,cho__food,편의점 신상디저트로 나온#허쉬초코트리치즈케익⠀ 한봉지에 총2조각이 들어있어요밑에 얇...,2024-11-27,"['#허쉬초코트리치즈케익⠀', '#편의점디저트', '#초코치즈케이크', '#초코트리..."

In [56]:
# ✅ 리뷰 데이터 전처리 (텍스트 정제)
import re

def clean_text(text):
    text = text.lower()  # 소문자로 변환
    text = re.sub(r"[^가-힣a-zA-Z0-9\s]", "", text)  # 한글, 영문, 숫자만 남기기
    text = re.sub(r"\s+", " ", text).strip()  # 연속된 공백 제거
    return text

df_new["리뷰"] = df_new["content"].apply(clean_text)

In [79]:
# ✅ 필요한 라이브러리 임포트
import torch
from transformers import BertForSequenceClassification

# ✅ 디바이스 설정 (GPU 사용 가능 여부 확인)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ✅ 저장된 모델 로드
num_labels = len(aspect_encoder.classes_) + len(sentiment_encoder.classes_)  # 속성 + 감성 레이블 개수
model = BertForSequenceClassification.from_pretrained("beomi/kcbert-base", num_labels=num_labels)
model.load_state_dict(torch.load("./absa_model.pth"))
model.to(device)
model.eval()

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at beomi/kcbert-base and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30000, 768, padding_idx=0)
      (position_embeddings): Embedding(300, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=6, bias=True)
)

In [81]:
# ✅ BERT 토크나이저 로드
tokenizer = BertTokenizer.from_pretrained("beomi/kcbert-base")

# ✅ 리뷰 데이터를 BERT 입력 형식으로 변환
def bert_tokenize(text):
    if pd.isna(text) or text.strip() == "":  # ✅ 빈 텍스트 처리
        return [0] * 64, [0] * 64  # 패딩 토큰 반환
    
    encoding = tokenizer(
        text,
        max_length=64,
        padding="max_length",
        truncation=True,
        return_tensors="pt"
    )
    return encoding["input_ids"][0].tolist(), encoding["attention_mask"][0].tolist()

df_new["input_ids"], df_new["attention_mask"] = zip(*df_new["content"].apply(bert_tokenize))

In [84]:
# ✅ 모델 예측 함수 정의
def predict_sentiment_aspect(input_ids, attention_mask):
    input_ids = torch.tensor(input_ids).unsqueeze(0).to(device)  # 배치 차원 추가
    attention_mask = torch.tensor(attention_mask).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs = model(input_ids, attention_mask=attention_mask)
        logits = outputs.logits

        # ✅ 속성과 감성 예측
        predicted_aspect_label = torch.argmax(logits[:, :len(aspect_encoder.classes_)], dim=1).cpu().item()
        predicted_sentiment_label = torch.argmax(logits[:, len(aspect_encoder.classes_):], dim=1).cpu().item()

        # ✅ 인코딩된 값을 원래 라벨(한글)로 변환
        predicted_aspect = aspect_encoder.inverse_transform([predicted_aspect_label])[0]
        predicted_sentiment = sentiment_encoder.inverse_transform([predicted_sentiment_label])[0]

    return predicted_aspect, predicted_sentiment

# ✅ df_new에 대해 모델 예측 실행
df_new["예측된 속성"], df_new["예측된 감성"] = zip(*df_new.apply(
    lambda row: predict_sentiment_aspect(row["input_ids"], row["attention_mask"]), axis=1))

KeyboardInterrupt:

In [86]:
df_new[['content','예측된 속성','예측된 감성']]

                                               content 예측된 속성 예측된 감성
0    #광고#디저트39저당디저트★판매처:#편의점 (세븐일레븐 단독)#디저트39 와 콜라보...     포장     긍정
1    #티라미수젤라또★구매처:#이마트★가격:5,980원오랜만에 이마트 갔다가 아이스크림 ...     포장     긍정
2    #잘익은쑥이야기★구매처:#편의점#세븐일레븐#GS25#CU★가격:2,000원편의점 빵...      맛     긍정
3    #비타민나무카라멜★구매처:#쿠팡#쿠팡로켓배송★가격: 3봉지 세트로 8,520원티벳에...     포장     부정
4    #아이스홍시★구입처:#편의점#세븐일레븐★가격: 1,800원(할인행사가격)갑자기 아이...     가격     긍정
..                                                 ...    ...    ...
295  스타벅스 신상으로 나온#메리베리베이글샌드⠀ 블루베리 베이글 + 베리맛 크림치즈+ 라...      맛     긍정
296  #협찬 애슐리 퀸즈에서 11월 28일에 시즌한정으로스테이크&와인페어링이 출시되서 연...     포장     긍정
297  GS25편의점 신상으로 나온#누룽지우리쌀파운드⠀ 생각보다 부드럽고 촉촉한편이었고파운...      맛     긍정
298  신상과자로 나온 오리온#꼬래밥콘스프맛⠀ 기존 고래밥과 달리 거북이🐢모양으로되어 있고...      맛     긍정
299  편의점 신상디저트로 나온#허쉬초코트리치즈케익⠀ 한봉지에 총2조각이 들어있어요밑에 얇...      맛     긍정

[300 rows x 3 columns]