In [10]:
import pandas as pd

df = pd.read_csv('seven_eleven_pb.csv')
df

                  상품명    가격                                            이미지_URL
0    다논)액티비아업플레인210ml  2200  https://www.7-eleven.co.kr/upload/product/8809...
1     다논)액티비아업딸기210ml  2200  https://www.7-eleven.co.kr/upload/product/8809...
2     덴마크)딸기딸기우유300ml  2000  https://www.7-eleven.co.kr/upload/product/8801...
3     덴마크)초코초코우유300ml  2000  https://www.7-eleven.co.kr/upload/product/8801...
4     덴마크)바나바나우유300ml  2000  https://www.7-eleven.co.kr/upload/product/8801...
..                ...   ...                                                ...
75     PB)단백질바(베리)50g  1500  https://www.7-eleven.co.kr/front/img/product/p...
76      PB)을지로약과팝콘80g  1700  https://www.7-eleven.co.kr/upload/product/8809...
77     PB)초코퐁당강냉이175g  3300  https://www.7-eleven.co.kr/front/img/product/p...
78  PB)new미용티슈200매*3입  9700  https://www.7-eleven.co.kr/upload/product/8809...
79  PB)마이멜로디베리베리팝콘80g  2000  https://www.7-eleven.co.kr/upload/product/8809...

[80 rows x 3 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   상품명      80 non-null     object
 1   가격       80 non-null     int64
 2   이미지_URL  80 non-null     object
dtypes: int64(1), object(2)
memory usage: 2.0+ KB

In [7]:
import pandas as pd

df_2 = pd.read_csv('seven_eleven_freshfood.csv')
df_2

                 상품명     가격                                            이미지_URL
0       삼립)바나나블루베리샌드   3300  https://www.7-eleven.co.kr/upload/product/8801...
1        롯데)매콤왕교자그라탕   4300  https://www.7-eleven.co.kr/upload/product/8801...
2      그린)머쉬룸투움바비프버거   3500  https://www.7-eleven.co.kr/upload/product/8809...
3    롯데)안유성명장 치킨난반정식   5500  https://www.7-eleven.co.kr/upload/product/8801...
4          그린)초코딸기샌드   3800  https://www.7-eleven.co.kr/upload/product/8809...
..               ...    ...                                                ...
138  그린)NEW햄참치마요네즈삼각   1200  https://www.7-eleven.co.kr/upload/product/8809...
139   예약)한끼연구소 제육비빔밥   8000  https://www.7-eleven.co.kr/upload/product/8801...
140    예약)한끼 바싹불고기정식  10000  https://www.7-eleven.co.kr/upload/product/8801...
141    예약)한끼연구소 유부초밥  11000  https://www.7-eleven.co.kr/upload/product/8809...
142  예약)한끼연구소 소불고기정식   9000  https://www.7-eleven.co.kr/upload/product/8801...

[143 rows x 3 columns]

In [8]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   상품명      143 non-null    object
 1   가격       143 non-null    int64
 2   이미지_URL  143 non-null    object
dtypes: int64(1), object(2)
memory usage: 3.5+ KB

In [9]:
df_2.describe()

                 가격
count    143.000000
mean    3755.244755
std     1883.833308
min     1100.000000
25%     2800.000000
50%     3500.000000
75%     4500.000000
max    11000.000000

In [15]:
import pandas as pd

df = pd.read_csv('gs25_fresh_food_by_category_modified.csv')
df

,category,title,price,img_url
0,도시락,뭘좋아할지몰라또만들었어1,6000,https://image.woodongs.com/imgsvr/item/GD_2700...
1,도시락,뭘좋아할지몰라다넣어봤어1,6000,https://image.woodongs.com/imgsvr/item/GD_2700...
2,도시락,혜자로운)베이컨김치볶음밥,3500,https://image.woodongs.com/imgsvr/item/GD_2700...
3,도시락,2단위로도시락매운김치,5500,https://image.woodongs.com/imgsvr/item/GD_2700...
4,도시락,3단위로도시락에그함박,6500,https://image.woodongs.com/imgsvr/item/GD_2700...
...,...,...,...,...
185,간편식,PIGNEW에그가먼저닭샐러드,3800,https://image.woodongs.com/imgsvr/item/GD_8801...
186,간편식,SB)케이준치킨치즈샐러드,4900,https://image.woodongs.com/imgsvr/item/GD_8809...
187,간편식,꽉)매콤돈까스스파게티1,5900,https://image.woodongs.com/imgsvr/item/GD_2700...
188,간편식,삼립)슈퍼슈프림치즈부리또,3200,https://image.woodongs.com/imgsvr/item/GD_8801...
189,간편식,삼립)불고기치즈부리또,3200,https://image.woodongs.com/imgsvr/item/GD_8801...

In [16]:
df['category'].value_counts()

category
김밥/주먹밥      61
간편식         57
햄버거/샌드위치    55
도시락         17
Name: count, dtype: int64

In [17]:
df_2 = pd.read_csv('gs25_pb_food_by_category_modified.csv')
df_2

,category,title,price,img_url
0,음료/커피,유어스)국내산생칡즙M,2000,https://image.woodongs.com/imgsvr/item/GD_8809...
1,음료/커피,유어스)꿀쌍화150ML,1800,https://image.woodongs.com/imgsvr/item/GD_8809...
2,음료/커피,유어스)커피빈디카페인아메리카,2700,https://image.woodongs.com/imgsvr/item/GD_8801...
3,음료/커피,유어스)하늘가득납작복숭아330ML,2100,https://image.woodongs.com/imgsvr/item/GD_8801...
4,음료/커피,유어스)하늘가득적포도330ML,2100,https://image.woodongs.com/imgsvr/item/GD_8801...
...,...,...,...,...
226,라면/가공식품,Y)오모리김치찌개라면(대컵),1850,https://image.woodongs.com/imgsvr/item/GD_8809...
227,라면/가공식품,Y)공화춘삼선짬뽕(봉지),1450,https://image.woodongs.com/imgsvr/item/GD_8801...
228,라면/가공식품,Y)틈새라면(소컵),1150,https://image.woodongs.com/imgsvr/item/GD_8801...
229,라면/가공식품,Y)틈새라면(봉지),1200,https://image.woodongs.com/imgsvr/item/GD_8801...
230,라면/가공식품,유어스)양반전복죽287G,4500,https://image.woodongs.com/imgsvr/item/GD_8801...

In [18]:
df_2['category'].value_counts()

category
과자/간식      115
음료/커피       61
라면/가공식품     28
유제품         27
Name: count, dtype: int64